---   

<h1 align="center">ExD</h1>
<h1 align="center">Course: Advanced Python Programming Language</h1>

---   

<h1 align="center">Constants</h1>

## _Constants.ipynb_
#### [Python Constants](https://docs.python.org/3/library/constants.html#)

**What is a Constant?**

Imagine you have a favorite toy. You never want to change it, right? It’s your special toy.

In Python, a constant is like that special toy. You give it a name, and you don’t change it. It stays the same while the program runs.

In [ ]:
SPEED_OF_LIGHT = 299792458  # meters per second


#### Here, SPEED_OF_LIGHT is a constant. We treat it as something that never changes. So, constants are special names for values that don’t change.

## Built-in Constants in Python
- Python has a small set of predefined constants that you can use without importing anything. These constants are always available in your Python program. Here’s a list of the most important built-in constants: 
| Constant         | Description                                                                                              |
|------------------|----------------------------------------------------------------------------------------------------------|
| `True`           | Boolean constant for true values. Example: `True == 1` is `True`.                                        |
| `False`          | Boolean constant for false values. Example: `False == 0` is `True`.                                      |
| `None`           | Represents the absence of a value or a null value. Example: `x = None`.                                  |
| `Ellipsis`       | Special constant (`...`) often used in slicing or placeholders. Example: `...`.                           |
| `NotImplemented` | Special constant indicating an operation is not implemented for a given type. Example: `__eq__` methods can return `NotImplemented`. |
| `__debug__`      | A constant that is `True` if Python is not started with the `-O` option (optimized mode). It’s `False` when running optimized Python. |


In [1]:
print(True)         # True
print(False)        # False

x = None
print(x)            # None

print(...)          # Ellipsis

def add(a, b):
    return NotImplemented  # Placeholder for not yet implemented function

print(__debug__)    # True by default

True
False
None
Ellipsis
True


### Ellipsis 

* It is used as a placeholder or for advanced slicing (mainly in multi-dimensional arrays like NumPy).
* It’s often used when you want to say: “Something should go here, but I’m not ready to write it yet.”

#### 1.Placeholder for Incomplete Code (Temporary)

In [2]:
def my_function():
    ...
    # This means: I'll fill this in later!

class MyClass:
    ...


###### This is like saying, “I’m still thinking about this part!”

#### 2.In Slicing (Advanced)

Let’s say you have a multi-dimensional array (e.g., in NumPy):

In [7]:
arr = np.arange(27).reshape(3, 3,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [8]:
arr[:,:,0]

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [9]:
import numpy as np
arr = np.arange(27).reshape(3, 3, 3)
print(arr)
print("-------------------------")
print(arr[..., 0])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
-------------------------
[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]


Here:

    ... means: "Keep all other dimensions as they are."

    So arr[..., 0] means: “Give me the first element of the last dimension across all dimensions.”

###### Why does ... mean “keep all dimensions as they are except the last one”?

When we use Ellipsis (...) in NumPy slicing, it’s a shortcut that says:

    "I don’t want to write all the colons (:) for every dimension, so just keep everything else the same."
    
If you wanted to select the first element of the last dimension without using ..., you’d write:  

In [ ]:
arr[:, :, 0]

This means:

  - : in the first dimension (take everything),

  - : in the second dimension (take everything),

  - 0 in the last dimension (take the first element).

But writing all those colons gets tiring for bigger arrays! So Python gives us a shortcut:
  - arr[..., 0]

| Dimension     | What it holds                   | Shape (Size)      |
| ------------- | ------------------------------- | ----------------- |
| 1st dimension | The **big blocks**              | 3 blocks          |
| 2nd dimension | The **rows inside each block**  | 3 rows per block  |
| 3rd dimension | The **columns inside each row** | 3 columns per row |

#### Think of it like:

    A block (1st dimension),

    Inside is a row (2nd dimension),

    And inside that row is a column (3rd dimension).

So the last dimension is the column.


In [10]:
arr[..., 2]

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

This says:

> "Keep everything else (: for all other dimensions), but in the last dimension, take index 0."

##### Why the last dimension?

Think of it this way:

   - If you write arr[0], you’re taking the first block in the first dimension.

   - If you write arr[..., 0], you’re taking the first item in the last dimension for all other dimensions.

So, ... fills in the missing colons.

| What you write      | What NumPy sees    |
|---------------------|--------------------|
| `arr[..., 0]`       | `arr[:, :, 0]`     |
| `arr[..., 1]`       | `arr[:, :, 1]`     |
| `arr[0, ..., 0]`    | `arr[0, :, 0]`     |
| `arr[0, 1, ...]`    | `arr[0, 1, :]`     |

 - ... is a shortcut for "all dimensions I didn't explicitly write."

 - It helps you select the right part of a multidimensional array without having to write all the colons.

 - The number you write (e.g., 0 in arr[..., 0]) is applied to the last remaining axis.

#### 3. Printing the Value

You can also see that ... is actually a constant by printing it:

In [12]:
print(Ellipsis)  # Output: Ellipsis
print(...)       # Output: Ellipsis

Ellipsis
Ellipsis


#### 4. In Type Hints 

When using Python typing for static type checking, ... is used in function signatures to mean any number of arguments. 

This tells type checkers: "This is a function that accepts any number of arguments."

 - Callable means: "This is a function (or something that can be called, like a function)."
 - The [...] inside Callable means: "I don’t care what arguments the function takes. It can take anything, any number of arguments, of any type."

In [30]:
from typing import Callable

f: Callable[..., int]  # Function takes any arguments, returns int


In [31]:
def foo(x, y):
    return 1

def bar(a, b, c, d):
    return 2


Both foo and bar can match the type Callable[..., int] because they can have any arguments.

#### What is Callable?

In Python, Callable is a special type hint from the typing module.

It simply means:

    "A thing that you can call like a function."


#### What is a Type Hint in Python?

A type hint is like a little note you leave in your code that tells:

    What kind of data a variable, function, or return value should hold.

It’s like saying:

    "Hey, this is what I expect this thing to be!"

But it doesn’t force Python to check it (Python is dynamically typed, so it won’t break your code if you mess up), but it helps humans (and tools like linters, code editors, etc.) understand your code better!

####  Without type hints:
It’s not clear what type name should be.

In [32]:
def greet(name):
    return f"Hello, {name}"
greet("Hello Class")
greet(1)

'Hello, 1'

####  With type hints:
Now it’s clear:

 - name should be a string (str),
 - the function will return a string (str).

In [33]:
def greet(name: str) -> str:
    return f"Hello, {name}"
greet(1.37)

'Hello, 1.37'

In [34]:
from typing import Callable

my_func: Callable[..., int]


In [35]:
from typing import Callable

def call_me_back(f: Callable[..., int]):
    result = f("hello", 123, True)
    print(result)

def my_function(a, b, c):
    return 42

a = call_me_back(my_function)  
print(a)

42
None


##### What does this mean?

- Callable[..., int] means:

      f can be any function that takes any number of arguments (... means any arguments),
        but it must return an integer (int).
     

#### 5. Custom Objects and Special Cases

In your own Python code, you can check if the user used an ellipsis (...). 

This is rare, but useful in special APIs or libraries.

In [36]:
def my_func(x):
    if x is Ellipsis:
        print("You passed an Ellipsis!")

my_func(...)
# Output: You passed an Ellipsis!


You passed an Ellipsis!


#### 6. In Slicing for __getitem__ (Special Methods)

When you define a custom class that supports slicing, you might handle Ellipsis inside `__getitem__`.

Some libraries (like TensorFlow, PyTorch) handle ellipsis this way.


#### What is slicing and __getitem__?

    In Python, slicing means selecting parts of a sequence (like a list or array) using the [] brackets with : notation.

In [37]:
my_list = [0, 1, 2, 3, 4]
print(my_list[1:3])  

[1, 2]


When you do obj[key] in Python, under the hood, Python calls a special method on the object called `__getitem__`.

In [38]:
#obj.__getitem__(key)
my_list.__getitem__(0)

0

In [39]:
print(my_list.__getitem__(slice(1, 3)))


[1, 2]


### Why handle Ellipsis inside `__getitem__`?

 - If you create your own class that supports slicing and indexing, you may want to accept and understand the Ellipsis in the slicing part.

In [40]:
class MyArray:
    def __getitem__(self, key):
        if key is Ellipsis:
            print("Ellipsis found!")
        else:
            print(f"Key is {key}")

arr = MyArray()
arr[...]  


Ellipsis found!


### Real-world use in libraries like TensorFlow and PyTorch

- Libraries for machine learning and scientific computing (like TensorFlow, PyTorch) deal with high-dimensional tensors.

- These tensors have many dimensions (like 4D or 5D).

- They allow users to use ... in slicing to easily select or manipulate multiple dimensions without typing all of them.

- So their custom `__getitem__` methods must recognize and correctly handle Ellipsis to work properly.

## What is NotImplemented? 

NotImplemented is a special constant in Python.

It’s used in operator overloading methods like:

 - `__add__`

 - `__eq__`

 - `__mul__`

 - `__sub__`

 - etc.
    
It tells Python:

    "I don’t know how to handle this operation, maybe the other object does."

If a method like `__eq__` or `__add__` returns NotImplemented, Python will try the other side’s method.

If both sides say NotImplemented, Python raises a TypeError.

In [41]:
class A:
    def __eq__(self, other):
        if isinstance(other, B):
            return NotImplemented  # A and B are never equal (A thinks so)
        return False  # Let other handle it
class B:
    def __eq__(self, other):
        if isinstance(other, A):
            return NotImplemented  # B thinks they are equal
        return NotImplemented
a = A()
b = B()

print(a == b)  # What happens here?
#print(b == a)


False


###  `__debug__`